model:
  cnn_channels: 32
  kernel_size: 3
  num_cnn_layers: 3
  num_fc_layers: 2
  flattened_size: 476288
  fc_features: 64
  num_classes: 23
  learning_rate: 0.001

model_training:
  num_epochs: 20

logger:
  project_name: dlmarines_public
  entity_name: dlmarines


